seed: 1001

locale: de_DE

columns:

  - column: bp_no
    strategy: unique_sequence
    format: "00{:08d}"
    start: 20000000

  - column: name
    strategy: faker
    provider: company

  - column: country
    strategy: categorical_resample

  - column: post_code
    strategy: faker
    provider: postcode

  - column: city
    strategy: faker
    provider: city

  - column: street
    strategy: faker
    provider: street_name

  - column: house_num1
    strategy: faker
    provider: building_number

  - column: additional_info
    strategy: unique_sequence
    format: "{:07d}"
    start: 1000000
