"""Regression test for package 003 (supplier migration).

Unlike packages 001/002, this package has no data/dataset.csv yet (no
NoiseEngine exists yet to generate it from clean_dataset.csv), so
BenchmarkPackage.load() can't be used here. Task/Schema/Dataset are loaded
directly instead. ground_truth.csv was generated by GroundTruthCreator itself
and manually spot-checked (filtering on a non-ISO date format, sequential
numbering, value mapping) before being committed as the golden reference.
"""

import pandas as pd

from migratebench.domain.common import load_yaml
from migratebench.domain.dataset import Dataset
from migratebench.domain.schema import Schema
from migratebench.domain.task import Task
from migratebench.generator.ground_truth_creator import GroundTruthCreator


def _load_task_and_target_schema(root):
    task = Task(**load_yaml(root / "task.yaml"))
    target_schema = Schema(**load_yaml(root / task.input.target_schema))
    return task, target_schema


def test_ground_truth_creator_reproduces_pkg3_ground_truth(pkg3_root):
    task, target_schema = _load_task_and_target_schema(pkg3_root)
    clean_df = Dataset(pkg3_root / "ground_truth" / "clean_dataset.csv").df

    actual = GroundTruthCreator().create_ground_truth(clean_df, task, target_schema)
    expected = Dataset(pkg3_root / "ground_truth" / "ground_truth.csv").df

    pd.testing.assert_frame_equal(
        actual.reset_index(drop=True).astype(str),
        expected.reset_index(drop=True).astype(str),
        check_dtype=False,
    )


def test_date_format_filtering_excludes_pre_2023_rows(pkg3_root):
    task, target_schema = _load_task_and_target_schema(pkg3_root)
    clean_df = Dataset(pkg3_root / "ground_truth" / "clean_dataset.csv").df

    result = GroundTruthCreator().create_ground_truth(clean_df, task, target_schema)

    # supplier no 1000002 has last_activity 30.10.2022 (before the cutoff)
    assert "1000002" not in set(result["additional_info"])
    # supplier no 1000000 has last_activity 26.07.2023 (after the cutoff)
    assert "1000000" in set(result["additional_info"])


def test_bp_no_is_unique_and_zero_padded(pkg3_root):
    task, target_schema = _load_task_and_target_schema(pkg3_root)
    clean_df = Dataset(pkg3_root / "ground_truth" / "clean_dataset.csv").df

    result = GroundTruthCreator().create_ground_truth(clean_df, task, target_schema)

    assert result["bp_no"].nunique() == len(result)
    assert set(result["bp_no"].str.len()) == {10}
    assert result["bp_no"].iloc[0] == "0020000000"
